### ISSUE TITLE
Only works with https:// 

### ISSUE THREAD

**Issue by jose920405** [Kimaia/react-native-hyperlinked-text#3]
when I try to support pages with http: or simply with www..

Example

http://www.whatever.com
www.whatever.com

Does not works

I have used
```
linkDefs = {[
     {
         regex: /(www|http:|https:)+[^\s]+[\w]/g,
     }
]}
```

and now if it detects them. But when I press this links www.whatever.com, they do not work. I'm not sure is this is a android requirement, but would be good know the best way for fix it, because in my case i can't guaranteeing https to http in all links.

I have tried adding
```
 onPress: (orig, text, url) => {
      // I change url to orig, because url come undefined for me.
      HyperlinkedText._openWebUrl(orig);
}
```
I am testing it with:

`linkDefault={ true }`

 I still can not works the links that only have `www.` or that are` http: `

*Example code:*
```
<HyperlinkedText style={styles.label}
    linkDefault={true}
    linkDefs={[
        {
            regex: /(www|http:|https:)+[^\s]+[\w]/g,
        }
    ]}
>
    {desc}
</HyperlinkedText>
```

but it does not work either

**Comment by daramasala** [comment]
Hi, sorry for the late reply.
The component detects both http and https links.
The reason your example does not work is probably because you did not implement the `onPress` property.
Checkout the [example app](https://github.com/Kimaia/react-native-hyperlinked-text/blob/2cd2817893d1ccbea622acc4196fb1a0a5f45410/HyperlinkedTextExample/app/app.js#L33).
